### ISSUE TITLE
Support Django 4.2

### ISSUE THREAD

**Issue by johnthagen** [jazzband/django-dbbackup#486]
# Feature Request

Add Django 4.2 to the automated CI testing suite.

# Issue

When attempting to add support for Django 4.2, the following error appears within CI:

```
ERROR Error sending data
  Traceback (most recent call last):
    File "/home/runner/work/django-dbbackup/django-dbbackup/.tox/py310-django42/lib/python3.10/site-packages/gnupg.py", line 155, in _copy_data
      outstream.write(data)
  TypeError: a bytes-like object is required, not 'str'
  ....ERROR Exception: Foo
    File "/home/runner/work/django-dbbackup/django-dbbackup/dbbackup/utils.py", line 120, in wrapper
      func(*args, **kwargs)
    File "/home/runner/work/django-dbbackup/django-dbbackup/dbbackup/tests/test_utils.py", line 81, in func
      raise Exception("Foo")
  
  .ERROR Exception: Foo
    File "/home/runner/work/django-dbbackup/django-dbbackup/dbbackup/utils.py", line 120, in wrapper
      func(*args, **kwargs)
    File "/home/runner/work/django-dbbackup/django-dbbackup/dbbackup/tests/test_utils.py", line 91, in func
      raise Exception("Foo")
  
  ..ERROR Error sending data
  Traceback (most recent call last):
    File "/home/runner/work/django-dbbackup/django-dbbackup/.tox/py310-django42/lib/python3.10/site-packages/gnupg.py", line 155, in _copy_data
      outstream.write(data)
  TypeError: a bytes-like object is required, not 'str'
```

https://github.com/jazzband/django-dbbackup/blob/790ec8bd297ef24cddfd2618d18d243abd15437e/dbbackup/tests/utils.py#L120-L122

https://github.com/jazzband/django-dbbackup/blob/790ec8bd297ef24cddfd2618d18d243abd15437e/dbbackup/tests/test_utils.py#L87-L100

### `python-gnupg`

https://github.com/jazzband/django-dbbackup/blob/790ec8bd297ef24cddfd2618d18d243abd15437e/requirements/tests.txt#L9

https://github.com/vsajip/python-gnupg/blob/6081e55ccb513a478a64eaa48e993cb40853851e/gnupg.py#L138

**Comment by johnthagen** [comment]
@Archmonger Any idea what might have [changed in Django 4.2](https://docs.djangoproject.com/en/4.2/releases/4.2/#backwards-incompatible-changes-in-4-2) to break this test? I don't see an obvious smoking gun.

**Comment by Archmonger** [comment]
Given that it's gnupg related, my first guess is it's either one of our gnupg calls to encrypt backup files.

Or, if Django core uses gnupg then it might be for the email backend. The stack trace does seem to indicate it happens in an email test.

**Comment by Archmonger** [comment]
I recommend jumping into your venv and directly editing `gnupg.py`.

Need to add a print statement right before that exception to see what we're trying to encrypt to narrow things down.

**Comment by johnthagen** [comment]
There is a lot of warning/error output in the test suite 😅 . It looks like the real test failure is:

```
  ======================================================================
  FAIL: test_set_options (dbbackup.tests.test_storage.Get_StorageTest)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/runner/work/django-dbbackup/django-dbbackup/.tox/py310-django42/lib/python3.10/site-packages/mock/mock.py", line 1423, in patched
      return func(*newargs, **newkeywargs)
    File "/home/runner/work/django-dbbackup/django-dbbackup/dbbackup/tests/test_storage.py", line 26, in test_set_options
      self.assertEqual(storage.storage.__module__, "django.core.files.storage")
  AssertionError: 'django.core.files.storage.filesystem' != 'django.core.files.storage'
  - django.core.files.storage.filesystem
  ?                          -----------
  + django.core.files.storage
```

This seems to be caused by refactors in the storage module in Django

- https://docs.djangoproject.com/en/4.2/releases/4.2/#in-memory-file-storage

**Comment by johnthagen** [comment]
Fixed the issue in

- #485
