### ISSUE TITLE
Incompatibility with django-storages 1.14

### ISSUE THREAD

**Issue by Sciencealone** [jazzband/django-dbbackup#489]
# Bug Report

## Describe the bug

Thank you for the great tool! Unfortunately, it seems incompatible now. Application with DB backup (S3) drops an error after upgrading django-storages from 1.13.2 to 1.14. The situation returns to normal after the downgrade.

- OS: Ubuntu
- Python 3.10.12
- django 4.2.5
- django-dbbackup 4.0.2

## To Reproduce

in `settings.py`:

````
INSTALLED_APPS = [
    ...,
    dbbackup,
    ...
]

DBBACKUP_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

 DBBACKUP_STORAGE_OPTIONS = { 
    'access_key': os.environ.get('AWS_ACCESS_KEY'), 
    'secret_key': os.environ.get('AWS_SECRET_ACCESS_KEY'), 
    'bucket_name': os.environ.get('DB_BACKUP_BUCKET'), 
    'default_acl': 'private'
 }
````
somewhere else in the code:
````
from django.core import management

management.call_command('dbbackup', '-z')
````

## Expected behavior

A database backup appears in S3 bucket.

## Screenshots or reproduction

````
Traceback (most recent call last):
   File "app_path/backup.py", line 35, in do_backup
     management.call_command('dbbackup', '-z')
   File "python_path/site-packages/django/core/management/__init__.py", line 194, in call_command
     return command.execute(*args, **defaults)
   File "python_path/site-packages/django/core/management/base.py", line 458, in execute
     output = self.handle(*args, **options)
   File "python_path/site-packages/dbbackup/utils.py", line 120, in wrapper
     func(*args, **kwargs)
   File "python_path/site-packages/dbbackup/management/commands/dbbackup.py", line 93, in handle
     self._save_new_backup(database)
   File "python_path/site-packages/dbbackup/management/commands/dbbackup.py", line 120, in _save_new_backup
     self.write_to_storage(outputfile, filename)
   File "python_path/site-packages/dbbackup/management/commands/_base.py", line 97, in write_to_storage
     self.storage.write_file(file, path)
   File "python_path/site-packages/dbbackup/storage.py", line 86, in write_file
     self.storage.save(name=filename, content=filehandle)
   File "python_path/site-packages/django/core/files/storage/base.py", line 38, in save
     name = self._save(name, content)
   File "python_path/site-packages/storages/backends/s3.py", line 461, in _save
   File "python_path/site-packages/boto3/s3/inject.py", line 725, in object_upload_fileobj
     return self.meta.client.upload_fileobj(
   File "python_path/site-packages/boto3/s3/inject.py", line 636, in upload_fileobj
     return future.result()
   File "python_path/dist-packages/s3transfer/futures.py", line 103, in result
     return self._coordinator.result()
   File "python_path/dist-packages/s3transfer/futures.py", line 266, in result
     raise self._exception
   File "python_path/dist-packages/s3transfer/tasks.py", line 139, in __call__
     return self._execute_main(kwargs)
   File "python_path/dist-packages/s3transfer/tasks.py", line 162, in _execute_main
     return_value = self._main(**kwargs)
   File "python_path/dist-packages/s3transfer/upload.py", line 758, in _main
     client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
   File "python_path/site-packages/botocore/client.py", line 535, in _api_call
     return self._make_api_call(operation_name, kwargs)
   File "python_path/site-packages/botocore/client.py", line 963, in _make_api_call
     http, parsed_response = self._make_request(
   File "python_path/site-packages/botocore/client.py", line 986, in _make_request
     return self._endpoint.make_request(operation_model, request_dict)
   File "python_path/site-packages/botocore/endpoint.py", line 119, in make_request
     return self._send_request(request_dict, operation_model)
   File "python_path/site-packages/botocore/endpoint.py", line 198, in _send_request
     request = self.create_request(request_dict, operation_model)
   File "python_path/site-packages/botocore/endpoint.py", line 134, in create_request
     self._event_emitter.emit(
   File "python_path/site-packages/botocore/hooks.py", line 412, in emit
     return self._emitter.emit(aliased_event_name, **kwargs)
   File "python_path/site-packages/botocore/hooks.py", line 256, in emit
     return self._emit(event_name, kwargs)
   File "python_path/site-packages/botocore/hooks.py", line 239, in _emit
     response = handler(**kwargs)
   File "python_path/site-packages/botocore/signers.py", line 105, in handler
     return self.sign(operation_name, request)
   File "python_path/site-packages/botocore/signers.py", line 189, in sign
     auth.add_auth(request)
   File "python_path/site-packages/botocore/auth.py", line 432, in add_auth
     self._inject_signature_to_request(request, signature)
   File "python_path/site-packages/botocore/auth.py", line 435, in _inject_signature_to_request
     auth_str = ['AWS4-HMAC-SHA256 Credential=%s' % self.scope(request)]
   File "python_path/site-packages/botocore/auth.py", line 384, in scope
     return '/'.join(scope)
 TypeError: sequence item 0: expected str instance, NoneType found
````

**Comment by gschurck** [comment]
I just tried on my project and it works for me with the current latest versions :
- Django 4.2.6
- django-dbbackup 4.0.2
- django-storages 4.14.2
- boto3 1.28.62
- botocore 1.31.62
- s3transfer 0.7.0

**Comment by Sciencealone** [comment]
@gschurck thank you for the check.

Unfortunately, my attempt with the suggested versions returned the error again. I tried both regular and encrypted (`management.call_command('dbbackup', '-z', '--encrypt')`) backups, but all seem valid only with `django-storages==1.13.2`.

**Comment by gschurck** [comment]
Tried with `-z` but still works.
The only dbbackup config I have in `settings.py` is a custom `S3Boto3Storage` Storage class for django-storages.
```py
class PrivateDatabaseBackupStorage(S3Boto3Storage):
    location = 'database_backups'
    default_acl = 'private'
    file_overwrite = False
```
```py
DBBACKUP_STORAGE = 'app.storage_backends.PrivateDatabaseBackupStorage'
```

**Comment by Sciencealone** [comment]
@gschurck thank you for the details - they helped to find a solution for this bug. It seems this parameter: `'access_key': os.environ.get('AWS_ACCESS_KEY')` (in `settings.py:DBBACKUP_STORAGE_OPTIONS`) is not enough for the updated AWS tools, so an environment variable with a correct name `AWS_ACCESS_KEY_ID` must be defined.

**Comment by gschurck** [comment]
Nice !
Strange that `DBBACKUP_STORAGE_OPTIONS` doesn't work alone though.
